'use client';

import PageLayout from '@/components/PageLayout';
import { motion } from 'framer-motion';

export default function DocsPage() {
  const sections = [
    {
      id: 'getting-started',
      title: 'Getting Started',
      content: [
        'Welcome to Vektra! This guide will help you get started with building beautiful interfaces using AI-powered design generation.',
        'Simply describe what you want to build in natural language, and Vektra will generate production-ready code for you.',
      ],
    },
    {
      id: 'how-it-works',
      title: 'How It Works',
      content: [
        '1. **Describe Your Vision**: Type what you want to build in the prompt box',
        '2. **AI Generation**: Our AI processes your request and generates clean, production-ready code',
        '3. **Customize**: Review and customize the generated code to match your needs',
        '4. **Deploy**: Export your code and deploy it anywhere',
      ],
    },
    {
      id: 'features',
      title: 'Key Features',
      content: [
        '**Natural Language Processing**: Describe interfaces in plain English',
        '**Production-Ready Code**: Get clean, maintainable code that follows best practices',
        '**Multiple Frameworks**: Support for React, Vue, Angular, and more',
        '**Responsive Design**: All generated code is mobile-first and responsive',
        '**Dark Mode**: Automatic dark mode support in generated interfaces',
      ],
    },
    {
      id: 'api',
      title: 'API Documentation',
      content: [
        'Coming soon! Our API will allow you to integrate Vektra\'s AI-powered design generation into your own tools and workflows.',
        'Key features will include:',
        '- REST API for programmatic access',
        '- Webhook support for real-time notifications',
        '- SDKs for popular programming languages',
        '- Authentication via API keys',
      ],
    },
    {
      id: 'faq',
      title: 'Frequently Asked Questions',
      content: [
        '**Q: What frameworks are supported?**',
        'A: Currently, we support React, Next.js, Vue, and Angular. More frameworks coming soon!',
        '',
        '**Q: Can I use the generated code commercially?**',
        'A: Yes! All code generated by Vektra is yours to use in any project, including commercial applications.',
        '',
        '**Q: Is my code stored on your servers?**',
        'A: We only store metadata about your projects. The actual code remains on your device unless you explicitly choose to save it.',
      ],
    },
    {
      id: 'support',
      title: 'Support',
      content: [
        'Need help? We\'re here for you!',
        '**Email**: support@vektra.com',
        '**Documentation**: Check out our guides and tutorials',
        '**Community**: Join our Discord server for community support',
        '',
        'For bug reports and feature requests, please visit our GitHub repository.',
      ],
    },
  ];

  return (
    <PageLayout>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Documentation</h1>
          <p className="text-lg text-muted max-w-2xl">
            Everything you need to know about using Vektra to build beautiful interfaces with AI.
          </p>
        </div>

        {/* Table of Contents */}
        <div className="mb-12 p-6 bg-surface border border-border rounded-xl">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-muted mb-4">
            Table of Contents
          </h2>
          <nav className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {sections.map((section) => (
              <a
                key={section.id}
                href={`#${section.id}`}
                className="text-sm hover:text-accent transition-colors"
              >
                {section.title}
              </a>
            ))}
          </nav>
        </div>

        {/* Content Sections */}
        <div className="space-y-12">
          {sections.map((section, index) => (
            <motion.section
              key={section.id}
              id={section.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="scroll-mt-24"
            >
              <h2 className="text-2xl md:text-3xl font-bold mb-4">{section.title}</h2>
              <div className="prose prose-neutral dark:prose-invert max-w-none">
                {section.content.map((paragraph, pIndex) => (
                  <p
                    key={pIndex}
                    className={`text-muted leading-relaxed ${
                      paragraph.startsWith('**') ? 'font-medium text-foreground' : ''
                    } ${paragraph === '' ? 'mb-2' : 'mb-4'}`}
                  >
                    {paragraph.split('**').map((part, i) =>
                      i % 2 === 0 ? (
                        <span key={i}>{part}</span>
                      ) : (
                        <strong key={i} className="font-semibold text-foreground">
                          {part}
                        </strong>
                      )
                    )}
                  </p>
                ))}
              </div>
            </motion.section>
          ))}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mt-16 p-8 bg-surface border border-border rounded-2xl text-center"
        >
          <h3 className="text-2xl font-bold mb-2">Ready to Get Started?</h3>
          <p className="text-muted mb-6">
            Start building beautiful interfaces with AI today.
          </p>
          <a
            href="/"
            className="inline-block bg-accent hover:bg-accent-hover text-white px-8 py-3 rounded-lg transition-colors font-medium"
          >
            Try Vektra Now
          </a>
        </motion.div>
      </motion.div>
    </PageLayout>
  );
}
